#!/usr/bin/env python
"""Importing & extracting files to and from the Mooltipass."""

from array import array
import logging
from optparse import OptionParser
import time
import sys

from mooltipy import MooltipassClient

def main_options():
    """Handles command-line interface, arguments & options."""

    usage = 'Usage: %prog {IMPORT|EXPORT} CONTEXT FILEPATH\n' + \
            'Example: %prog import ssh_key ~/.ssh/id_rsa'

    parser = OptionParser(usage)

    (options, args) = parser.parse_args()

    if not args[0].lower() in ['import', 'export']:
        parser.error('Action must be import or export; see --help.')
        sys.exit(0)

    if not len(args) == 3:
        parser.error('Incorrect number of arguments; see --help.')
        sys.exit(0)

    print(args)

    return (options, args)

if __name__ == '__main__':

    (options, args) = main_options()

    logging.basicConfig(
            format='%(levelname)s\t %(funcName)s():\t %(message)s',
            level=logging.DEBUG)

    action = args[0]
    context = args[1]
    filepath = args[2]

    mooltipass = MooltipassClient()

    # Ping the mooltipass, an integral part of the initialization process.
    if mooltipass is None:
        print('Mooltipass is None, this is a problem.')
        sys.exit(0)

    if not mooltipass.ping():
        logging.error('Mooltipass did not reply to a ping request!')
        print('failure')
        sys.exit(0)

    # Ensure Mooltipass status
    quiet_bool = False
    while True:
        status = mooltipass.get_status()
        if status == 5:
            break
        logging.debug('Status != 5... it is: {0}'.format(status))
        if not quiet_bool:
            print('Insert a card and unlock the Mooltipass...')
        quiet_bool = True
        time.sleep(2)

    # Handle context
    while True:
        if mooltipass.set_data_context(context):
            logging.debug('Set context ' + context)
            break
        else:
            if action == 'export':
                print("Context does not exist; can't export.")
                sys.exit(0)
            if not mooltipass.add_data_context(context):
                print('User decliend to add context.')
                sys.exit(0)
            logging.debug('Context added')
            time.sleep(1)

    if action == 'import':
        with open(filepath, 'rb') as fin:
            data = array('B',fin.read())
        if len(data) > 15000:
            print('That file appears to be greater than ~15000 bytes which is too large.')
            sys.exit(0)
        mooltipass.write_data_context(data)
    else:
        data = mooltipass.read_data_context()
        with open(filepath, 'wb') as fout:
            data.tofile(fout)

    # TODO: Pretty important
    #   * Alias argument "extract" as alternative to "export" because annoying
    #   * Replace optparse with argparse; python3 compatibility
    #   * I'm encountering errors sending ~> 16KB to a data service on the unit
    # TODO: Eventually
    #   * Some indication of progress -- transfer can be slow.
    #   * List data contexts
    #   * Delete data contexts
