# Commands
# https://github.com/limpkin/mooltipass/tree/master/source_code/src/USB
CMD_DEBUG               = 0xA0
CMD_PING                = 0xA1
CMD_VERSION             = 0xA2
CMD_CONTEXT             = 0xA3
CMD_GET_LOGIN           = 0xA4
CMD_GET_PASSWORD        = 0xA5
CMD_SET_LOGIN           = 0xA6
CMD_SET_PASSWORD        = 0xA7
CMD_CHECK_PASSWORD      = 0xA8
CMD_ADD_CONTEXT         = 0xA9
CMD_SET_BOOTLOADER_PWD  = 0xAA
CMD_JUMP_TO_BOOTLOADER  = 0xAB
CMD_GET_RANDOM_NUMBER   = 0xAC
CMD_START_MEMORYMGMT    = 0xAD
CMD_IMPORT_MEDIA_START  = 0xAE
CMD_IMPORT_MEDIA        = 0xAF
CMD_IMPORT_MEDIA_END    = 0xB0
CMD_SET_MOOLTIPASS_PARM = 0xB1
CMD_GET_MOOLTIPASS_PARM = 0xB2
CMD_RESET_CARD          = 0xB3
CMD_READ_CARD_LOGIN     = 0xB4
CMD_READ_CARD_PASS      = 0xB5
CMD_SET_CARD_LOGIN      = 0xB6
CMD_SET_CARD_PASS       = 0xB7
CMD_ADD_UNKNOWN_CARD    = 0xB8
CMD_MOOLTIPASS_STATUS   = 0xB9
CMD_FUNCTIONAL_TEST_RES = 0xBA
CMD_SET_DATE            = 0xBB
CMD_SET_UID             = 0xBC
CMD_GET_UID             = 0xBD
CMD_SET_DATA_SERVICE    = 0xBE
CMD_ADD_DATA_SERVICE    = 0xBF
CMD_WRITE_32B_IN_DN     = 0xC0
CMD_READ_32B_IN_DN      = 0xC1
CMD_CANCEL_USER_REQUEST = 0xC3
CMD_READ_FLASH_NODE     = 0xC5
CMD_WRITE_FLASH_NODE    = 0xC6
CMD_GET_FAVORITE        = 0xC7
CMD_SET_FAVORITE        = 0xC8
CMD_GET_STARTING_PARENT = 0xC9
CMD_SET_STARTING_PARENT = 0xCA
CMD_GET_CTRVALUE        = 0xCB
CMD_SET_CTRVALUE        = 0xCC
CMD_ADD_CARD_CPZ_CTR    = 0xCD
CMD_GET_CARD_CPZ_CTR    = 0xCE
CMD_CARD_CPZ_CTR_PACKET = 0xCF
CMD_GET_30_FREE_SLOTS   = 0xD0
CMD_GET_DN_START_PARENT = 0xD1
CMD_SET_DN_START_PARENT = 0xD2
CMD_END_MEMORYMGMT      = 0xD3

# Mooltipass settings
# https://github.com/limpkin/mooltipass/blob/4469e522b32f23e081a0c6c59603ff51136501b0/source_code/src/LOGIC/logic_eeprom.c
USER_PARAM_INIT_KEY_PARAM        = 0
KEYBOARD_LAYOUT_PARAM            = 1  #Keyboard layout                            default ID_KEYB_EN_US_LUT
USER_INTER_TIMEOUT_PARAM         = 2  #User interaction timeout                   default 15secs
LOCK_TIMEOUT_ENABLE_PARAM        = 3  #Lock timeout enabled                       default false
LOCK_TIMEOUT_PARAM               = 4  #Lock timeout value                         default 60mins
TOUCH_DI_PARAM                   = 5  #Detection integrator value                 default 6 consecutive samples
TOUCH_WHEEL_OS_PARAM_OLD         = 6  #{DEPRECATED}                               default 0
TOUCH_PROX_OS_PARAM              = 7  #Proximity sensing key                      default 0x73
OFFLINE_MODE_PARAM               = 8  #Offline mode enabled                       default false
SCREENSAVER_PARAM                = 9  #Screen saver enabled                       default false
TOUCH_CHARGE_TIME_PARAM          = 10 #Datasheet default value for charge time    default 0
TOUCH_WHEEL_OS_PARAM0            = 11 #Touch wheel oversample (one bit gain)      default 0x21
TOUCH_WHEEL_OS_PARAM1            = 12 #Touch wheel oversample (one bit gain)      default 0x21
TOUCH_WHEEL_OS_PARAM2            = 13 #Touch wheel oversample (one bit gain)      default 0x21
FLASH_SCREEN_PARAM               = 14 #Flashy screen enabled                      default true
USER_REQ_CANCEL_PARAM            = 15 #{DEPRECATED} Cancel user requests          default true
TUTORIAL_BOOL_PARAM              = 16 #Tutorial enabled                           default true
SCREEN_SAVER_SPEED_PARAM         = 17 #Speed of the screen saver                  default 15
LUT_BOOT_POPULATING_PARAM        = 18 #Credential LUT populating at card insert   default true
KEY_AFTER_LOGIN_SEND_BOOL_PARAM  = 19 #Key sent after login enabled               default true
KEY_AFTER_LOGIN_SEND_PARAM       = 20 #key sent after login value                 default KEY_TAB
KEY_AFTER_PASS_SEND_BOOL_PARAM   = 21 #Key sent after password enabled            default true
KEY_AFTER_PASS_SEND_PARAM        = 22 #Key sent after password value              default KEY_RETURN
DELAY_AFTER_KEY_ENTRY_BOOL_PARAM = 23 #Delay when a character is typed enabled    default false
DELAY_AFTER_KEY_ENTRY_PARAM      = 24 #Delay when a character is typed value      default 5ms
INVERTED_SCREEN_AT_BOOT_PARAM    = 25 #Invert the screen at boot                  default false
MINI_OLED_CONTRAST_CURRENT_PARAM = 26 #Contrast of oled display                   default 0x80
MINI_LED_ANIM_MASK_PARAM         = 27 #LED animation mask                         default 0xFF
MINI_KNOCK_DETECT_ENABLE_PARAM   = 28 #Knock detection enabled                    default false
MINI_KNOCK_THRES_PARAM           = 29 #Threshold for knock detection              default 8
LOCK_UNLOCK_FEATURE_PARAM        = 30 #Lock/Unlock from computer                  default LF_EN_MASK
HASH_DISPLAY_FEATURE_PARAM       = 31 #Display hash when unlocking the card       default false
RANDOM_INIT_PIN_PARAM            = 32 #Randomize PIN when card inserted           default false
